import cmath
import math
import unittest

from lcm_sawtooth_endpoint_conductor_obstruction import (
    endpoint_conductor_energy_bound_receipt,
    two_conductor_endpoint_obstruction_receipt,
)


class LcmSawtoothEndpointConductorObstructionTests(unittest.TestCase):
    def test_endpoint_bound_matches_direct_primitive_frequency_sum(self):
        for modulus, conductor in (
                (101, 30), (101, 211), (101, 2310), (251, 3990),
                (11, 1009)):
            receipt = endpoint_conductor_energy_bound_receipt(
                modulus, conductor)
            length = modulus - 1
            direct = sum(abs(sum(
                cmath.exp(2j * math.pi * k * x / conductor)
                for x in range(length))) ** 2
                for k in range(1, conductor)
                if math.gcd(k, conductor) == 1)
            self.assertAlmostEqual(
                receipt["primitive_conductor_energy"], direct,
                delta=1e-7 * max(1.0, direct))
            self.assertLessEqual(
                receipt["endpoint_energy_fraction"],
                receipt["proved_endpoint_energy_fraction_bound"] + 1e-12)
            self.assertTrue(receipt["endpoint_dilution_bound_proved"])
        self.assertLess(
            endpoint_conductor_energy_bound_receipt(11, 1009)[
                "proved_endpoint_energy_fraction_bound"],
            0.4)

    def test_two_supported_composite_conductors_force_quadratic_loss(self):
        # 221=lcm(13,17) and 437=lcm(19,23), so both occur in the
        # primitive-conductor support generated by retained divisors <=23.
        receipt = two_conductor_endpoint_obstruction_receipt(
            101, 10, 221, 437)
        self.assertEqual(
            set(receipt["cross_endpoint_reduced_denominators"]), {96577})
        self.assertGreaterEqual(
            receipt["normalized_cross_endpoint_envelope"],
            receipt["proved_normalized_lower_bound"])
        self.assertGreater(
            receipt["proved_normalized_lower_bound"], 3200)
        self.assertTrue(
            receipt["generic_subpower_conductor_energy_comparison_refuted"])
        self.assertFalse(receipt["structured_polynomial_family_refuted"])
        self.assertFalse(receipt["prime_averaged_endpoint_bound_refuted"])

    def test_invalid_obstruction_geometry_is_rejected(self):
        with self.assertRaisesRegex(ValueError, "obstruction range"):
            two_conductor_endpoint_obstruction_receipt(101, 10, 210, 330)
        with self.assertRaisesRegex(ValueError, "squarefree"):
            endpoint_conductor_energy_bound_receipt(101, 12)


if __name__ == "__main__":
    unittest.main()
