"""Audit whether the q286-WBSS full coefficient globally descends to four moduli.

The prior tail-support LP found that adding only modulus 130 to the dominant
support moduli 70, 154, and 286 closes the 24-row stress fixture.  This script
checks whether that was sample luck or an exact finite algebraic compression.
The stronger test is unit-level descent:

    the full q286-WBSS unit coefficient f(u) lies in the additive row span
    generated by total mass plus projections to moduli 70, 130, 154, and 286.

If this holds, then for every even target residue a modulo 10010 the reflected
orbit coefficient Phi_a({u,a-u})=(f(u)+f(a-u))/2 inherits the same additive
projection form.

If true, the four-modulus projection target is not just a renamed finite LP
patch.  It is still not a prime distribution theorem and does not prove
Goldbach; it only identifies the lower projection data that would determine
the full signed expectation.
"""

from __future__ import annotations

import json
import math
import subprocess
import sys
from pathlib import Path

import numpy as np
from scipy.sparse import csr_matrix, vstack
from scipy.sparse.linalg import lsqr


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "evidence" / "q286-wbss-four-modulus-span-identity-audit.json"
PERIOD = 10010
TOLERANCE = 1e-10

DOMINANT_MODULI = (70, 154, 286)
FOUR_MODULI = (70, 130, 154, 286)
ALL_SUPPORT_MODULI = (10, 14, 22, 26, 70, 130, 154, 286)

MODULUS_FAMILIES = {
    "dominant_support_moduli": DOMINANT_MODULI,
    "four_modulus_support": FOUR_MODULI,
    "all_coefficient_support_moduli": ALL_SUPPORT_MODULI,
}
SPOT_TARGET_RESIDUES = (0, 2, 4766, 554, 9078, 6426, 9974)

sys.path.insert(0, str(ROOT))

from tools.build_q286_cone_duality_l1_uniformity_candidate import (  # noqa: E402
    combined_fixed_strict_central_coefficient_receipt,
    period_full_unit_coefficients,
    prepare_support_context,
)
from tools.build_q286_wbss_main_term_sign_audit import finite_summary  # noqa: E402


def source_commit():
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
    except (OSError, subprocess.CalledProcessError):
        return None


def json_ready(value):
    if isinstance(value, dict):
        return {str(key): json_ready(item) for key, item in value.items()}
    if isinstance(value, (tuple, list)):
        return [json_ready(item) for item in value]
    if isinstance(value, np.ndarray):
        return json_ready(value.tolist())
    if isinstance(value, np.generic):
        return json_ready(value.item())
    if isinstance(value, float) and not math.isfinite(value):
        return None
    return value


def projection_rowspace(orbits, moduli):
    matrices = [csr_matrix(np.ones((1, len(orbits)), dtype=np.float64))]
    row_counts = {"total_mass": 1}
    for modulus in moduli:
        residues = sorted({
            int(unit % modulus)
            for orbit in orbits
            for unit in orbit
        })
        residue_index = {residue: index for index, residue in enumerate(residues)}
        data = []
        row_indexes = []
        column_indexes = []
        for column, orbit in enumerate(orbits):
            scale = 1.0 / len(orbit)
            for unit in orbit:
                row_indexes.append(residue_index[int(unit % modulus)])
                column_indexes.append(column)
                data.append(scale)
        matrix = csr_matrix(
            (data, (row_indexes, column_indexes)),
            shape=(len(residues), len(orbits)),
            dtype=np.float64,
        )
        matrices.append(matrix)
        row_counts[str(modulus)] = len(residues)
    return vstack(matrices, format="csr"), row_counts


def coefficient_span_residual(phi, rowspace):
    solved = lsqr(rowspace.T, phi, atol=1e-12, btol=1e-12, iter_lim=2000)
    residual = phi - rowspace.T @ solved[0]
    scale = max(1.0, float(np.linalg.norm(phi)))
    return {
        "relative_l2_residual": float(np.linalg.norm(residual) / scale),
        "l2_residual": float(np.linalg.norm(residual)),
        "max_abs_residual": float(np.max(np.abs(residual))),
        "lsqr_iterations": int(solved[2]),
        "lsqr_stop_code": int(solved[1]),
        "lsqr_condition_estimate": float(solved[6]),
        "row_count": int(rowspace.shape[0]),
    }


def even_target_residues():
    return tuple(range(0, PERIOD, 2))


def build_unit_row(all_units, full_coefficients, principal):
    unit_columns = tuple((unit,) for unit in all_units)
    phi = np.asarray([
        full_coefficients[unit].real / principal
        for unit in all_units
    ], dtype=np.float64)
    family_rows = {}
    for family, moduli in MODULUS_FAMILIES.items():
        rowspace, row_counts = projection_rowspace(unit_columns, moduli)
        family_rows[family] = {
            "moduli": list(moduli),
            "projection_row_counts": row_counts,
            **coefficient_span_residual(phi, rowspace),
        }
    return {
        "unit_count": len(all_units),
        "coefficient_l2_norm": float(np.linalg.norm(phi)),
        "families": family_rows,
    }


def reflection_orbits(target_residue, units):
    unit_set = set(units)
    seen = set()
    orbits = []
    for unit in units:
        if unit in seen:
            continue
        reflected = (target_residue - unit) % PERIOD
        if reflected not in unit_set:
            raise AssertionError("reflection left admissible support")
        orbit = tuple(sorted({unit, reflected}))
        seen.update(orbit)
        orbits.append(orbit)
    return tuple(orbits)


def build_residue_row(target_residue, all_units, full_coefficients, principal):
    admissible_units = tuple(
        unit for unit in all_units
        if math.gcd((target_residue - unit) % PERIOD, PERIOD) == 1
    )
    orbits = reflection_orbits(target_residue, admissible_units)
    phi = np.asarray([
        math.fsum(
            (full_coefficients[unit].real / principal)
            for unit in orbit
        ) / len(orbit)
        for orbit in orbits
    ], dtype=np.float64)
    uniform = np.asarray(
        [len(orbit) / len(admissible_units) for orbit in orbits],
        dtype=np.float64,
    )
    family_rows = {}
    for family, moduli in MODULUS_FAMILIES.items():
        rowspace, row_counts = projection_rowspace(orbits, moduli)
        family_rows[family] = {
            "moduli": list(moduli),
            "projection_row_counts": row_counts,
            **coefficient_span_residual(phi, rowspace),
        }
    return {
        "target_residue": int(target_residue),
        "target_mod_286": int(target_residue % 286),
        "admissible_unit_count": len(admissible_units),
        "reflection_orbit_count": len(orbits),
        "uniform_full_action": float(np.dot(uniform, phi)),
        "coefficient_l2_norm": float(np.linalg.norm(phi)),
        "families": family_rows,
    }


def summarize_family(rows, family):
    family_rows = [row["families"][family] for row in rows]
    exact_rows = [
        row for row, family_row in zip(rows, family_rows)
        if family_row["relative_l2_residual"] <= TOLERANCE
    ]
    failures = [
        {
            "target_residue": row["target_residue"],
            "target_mod_286": row["target_mod_286"],
            "reflection_orbit_count": row["reflection_orbit_count"],
            "relative_l2_residual": family_row["relative_l2_residual"],
            "max_abs_residual": family_row["max_abs_residual"],
            "lsqr_stop_code": family_row["lsqr_stop_code"],
            "lsqr_iterations": family_row["lsqr_iterations"],
            "row_count": family_row["row_count"],
        }
        for row, family_row in zip(rows, family_rows)
        if family_row["relative_l2_residual"] > TOLERANCE
    ]
    worst_rows = sorted(
        (
            {
                "target_residue": row["target_residue"],
                "target_mod_286": row["target_mod_286"],
                "reflection_orbit_count": row["reflection_orbit_count"],
                "relative_l2_residual": family_row["relative_l2_residual"],
                "max_abs_residual": family_row["max_abs_residual"],
                "lsqr_stop_code": family_row["lsqr_stop_code"],
                "lsqr_iterations": family_row["lsqr_iterations"],
                "row_count": family_row["row_count"],
            }
            for row, family_row in zip(rows, family_rows)
        ),
        key=lambda item: (-item["relative_l2_residual"], item["target_residue"]),
    )[:12]
    return {
        "row_count": len(rows),
        "exact_span_count": len(exact_rows),
        "span_failure_count": len(failures),
        "maximum_relative_l2_residual": max(
            row["relative_l2_residual"] for row in family_rows),
        "maximum_max_abs_residual": max(
            row["max_abs_residual"] for row in family_rows),
        "relative_l2_residual_summary": finite_summary(
            row["relative_l2_residual"] for row in family_rows),
        "max_abs_residual_summary": finite_summary(
            row["max_abs_residual"] for row in family_rows),
        "lsqr_iteration_summary": finite_summary(
            row["lsqr_iterations"] for row in family_rows),
        "row_count_summary": finite_summary(
            row["row_count"] for row in family_rows),
        "first_failures": failures[:12],
        "worst_rows": worst_rows,
    }


def build_receipt():
    context = prepare_support_context()
    context["coefficient"] = combined_fixed_strict_central_coefficient_receipt()
    full_coefficients = period_full_unit_coefficients(context)
    principal = float(context["principal_mean"].real)
    all_units = tuple(
        residue for residue in range(PERIOD)
        if math.gcd(residue, PERIOD) == 1
    )
    unit_row = build_unit_row(all_units, full_coefficients, principal)
    rows = [
        build_residue_row(
            target_residue,
            all_units,
            full_coefficients,
            principal,
        )
        for target_residue in SPOT_TARGET_RESIDUES
    ]
    summary = {
        family: summarize_family(rows, family)
        for family in MODULUS_FAMILIES
    }
    unit_summary = {
        family: row
        for family, row in unit_row["families"].items()
    }
    four = summary["four_modulus_support"]
    dominant = summary["dominant_support_moduli"]
    unit_four_exact = (
        unit_summary["four_modulus_support"]["relative_l2_residual"]
        <= TOLERANCE
    )
    return {
        "schema_version": 1,
        "source_commit": source_commit(),
        "status_boundary": (
            "finite algebraic span audit only; it proves no binary-prime "
            "projection theorem, signed discrepancy theorem, q286 threshold "
            "theorem, strict-central Goldbach theorem, or Goldbach proof"
        ),
        "goldbach_proved": False,
        "four_modulus_projection_theorem_proved": False,
        "signed_discrepancy_theorem_proved": False,
        "candidate": {
            "name": "global four-modulus coefficient span identity",
            "mechanism": (
                "Check whether the q286-WBSS full unit coefficient is "
                "determined by total mass and additive projections to "
                "moduli 70, 130, 154, and 286.  Unit-level descent implies "
                "the same span statement for every reflected target-orbit "
                "coefficient."
            ),
            "prediction": (
                "If the four-modulus unit residual is numerical zero while "
                "the dominant-only family fails, modulus 130 is a genuine "
                "missing projection coordinate rather than a stress-sample "
                "patch."
            ),
            "falsifier": (
                "A nonzero four-modulus unit residual falsifies this stronger "
                "identity.  If that happens, the slower target-by-target "
                "residue-span check is required."
            ),
            "smallest_test": (
                "Fit the full coefficient on all units modulo 10010 using "
                "only additive residue projections to the proposed moduli, "
                "then replay representative target-orbit consequences.  No "
                "prime counts or LP optimization are used."
            ),
            "novelty_label": "new-to-this-task",
        },
        "target_residue_period": PERIOD,
        "even_target_residue_count": len(even_target_residues()),
        "unit_level_identity_implies_all_even_target_residues": bool(
            unit_four_exact),
        "implied_exact_even_target_residue_count": (
            len(even_target_residues()) if unit_four_exact else 0),
        "modulus_families": {
            name: list(moduli) for name, moduli in MODULUS_FAMILIES.items()
        },
        "unit_level_summary": unit_summary,
        "spot_target_residue_summary": summary,
        "spot_target_residues": list(SPOT_TARGET_RESIDUES),
        "representative_rows": {
            "first": rows[0],
            "dominant_worst": dominant["worst_rows"][0],
            "four_modulus_worst": four["worst_rows"][0],
        },
        "decision": (
            "If the four-modulus unit residual is numerical zero, this is a "
            "real finite algebraic compression of the full coefficient and it "
            "implies the target-orbit span statement for all 5005 even "
            "residues.  The remaining hole then moves to proving actual "
            "strict-central binary-prime projection control for those four "
            "moduli.  If it fails, the four-modulus route is only a "
            "stress-fixture artifact."
        ),
    }


def main():
    OUT.write_text(
        json.dumps(json_ready(build_receipt()), indent=2, sort_keys=True)
        + "\n",
        encoding="utf-8",
    )
    print(OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
